/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 25 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <main.h>

int main(void)
{
  GLCD_Init();
  GLCD_sendChar('A')

  while (1)
  {
  };
}
