/* Main.c file generated by New Project wizard
 *
 * Created:   lun. ene. 31 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include "main.h"

float temp,humidity;
char str[30];
RTC_TIME_t time;
RTC_DATE_t date;

int main (void){
  GLCD_Init();
  DS1307_Init();
  DHT22_Init();
  delay_ms(100);
  GLCD_drawImage(0,0,(uint8_t *)welcome_screen,GLCD_WIDTH,GLCD_HEIGHT);
  delay_ms(500);
  while(1){
    delay_ms(500);
    DHT22_GetTemp_Humidity(&temp, &humidity);
    DS1307_get_time(&time);
    DS1307_get_date(&date);
    
    sprintf(str,"Temp: %.2f",temp,humidity);
    GLCD_setXY(3,1);
    GLCD_sendString(str);

    sprintf(str,"Humidity: %.2f",humidity);
    GLCD_setXY(3,2);
    GLCD_sendString(str);

    sprintf(str,"Time: %02d:%02d:%02d",time.hours,time.minutes,time.seconds);
    GLCD_setXY(3,3);
    GLCD_sendString(str);

    sprintf(str,"Date: %02d/%02d/%02d",date.date,date.month,date.year);
    GLCD_setXY(3,4);
    GLCD_sendString(str);
  }
  return 0;
}
