/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 25 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <main.h>

int main(void)
{
  GLCD_Init();
  GLCD_sendChar('A');

  delay_ms(1);
  delay_ms(10);
  delay_ms(100);
  delay_us(1);
  delay_us(10);
  delay_us(100);

  while (1)
  {
  };
}
