/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 25 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <main.h>

int main(void)
{

  // Write your code here
  /* AUX VARIABLES */
  /*
   char buf[50];
   char onMsg[] = "ON\n\r";
   char offMsg[] = "OFF\n\r";
   int dayCounter = 0;
    */

  unsigned char n5110_buffer[6][84]; //6 Rows 84 Columns

  /* DISPLAY IMAGES*/
  /*Por alguna magica razon, no funcionan las IMAGENES en Proteus, pero si funcionan en el codigo compilado de Keil*/
  /* INDEX 
	 0 = NO-DAY-SELECTED
	 1 = LUNES
	 2 = MARTES
	 3 = MIERCOLES
	 4 = JUEVES
	 5 = VIERNES
	 6 = SABADO
	 7 = DOMINGO
   */



  /* SPI 1 Init*/
  spi_init(1);

  /* N5110 Init */
  n5110_init(1);

  n5110_clear();
  n5110_clear_buffer(n5110_buffer);
  delay_ms(1000);

  n5110_update_str_buffer(0, 0, "HH:MM:SS", n5110_buffer);
  delay_ms(1000);
  n5110_print_buffer(n5110_buffer);

  while (1)
  {
  };
}
